name = "k3-swarm"
main = "worker.ts"
compatibility_date = "2025-03-01"

[[durable_objects.bindings]]
name = "REGISTRY"
class_name = "Registry"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Registry"]

[vars]
ACCESS_TOKEN_TTL_SEC = "3600"
