#!/usr/bin/env bash
# One-time Cloudflare tunnel setup for MoonTail volunteers.
# Free Cloudflare account — no Zero Trust / Access / credit card required.
set -euo pipefail

MOONTAIL_DIR="${MOONTAIL_DIR:-$HOME/.moontail}"
CREDS_DIR="$MOONTAIL_DIR/.cloudflared"
CFG="$MOONTAIL_DIR/cloudflared-volunteer.yml"
CONFIG="$MOONTAIL_DIR/config"
RPC_PORT="${MOONTAIL_RPC_PORT:-50052}"

if ! command -v cloudflared >/dev/null; then
  echo "Install cloudflared first:"
  echo "  https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/"
  exit 1
fi

TUNNEL_NAME="${MOONTAIL_TUNNEL_NAME:-moontail-$(whoami 2>/dev/null || hostname | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9-' | head -c 32)}"
HOSTNAME="${MOONTAIL_TUNNEL_HOSTNAME:-}"

echo "==> MoonTail volunteer tunnel (free Cloudflare account)"
echo "    Tunnel name: $TUNNEL_NAME"
echo ""

CERT="$HOME/.cloudflared/cert.pem"
if [[ ! -f "$CERT" ]]; then
  echo "==> Log in to Cloudflare (browser opens — free account OK)"
  cloudflared tunnel login
fi

mkdir -p "$CREDS_DIR" "$MOONTAIL_DIR"

if ! cloudflared tunnel list 2>/dev/null | awk '{print $2}' | grep -qx "$TUNNEL_NAME"; then
  echo "==> Creating tunnel: $TUNNEL_NAME"
  cloudflared tunnel create "$TUNNEL_NAME"
fi

TUNNEL_ID="$(cloudflared tunnel list 2>/dev/null | awk -v n="$TUNNEL_NAME" '$2 == n { print $1; exit }')"
if [[ -z "$TUNNEL_ID" ]]; then
  echo "Could not resolve tunnel ID for $TUNNEL_NAME"
  exit 1
fi

SRC_CRED="$HOME/.cloudflared/${TUNNEL_ID}.json"
if [[ ! -f "$SRC_CRED" ]]; then
  echo "Missing credentials: $SRC_CRED"
  exit 1
fi
cp "$SRC_CRED" "$CREDS_DIR/credentials.json"

if [[ -z "$HOSTNAME" ]]; then
  echo ""
  read -rp "Public hostname for this GPU (e.g. gpu-you.example.com or auto DNS): " HOSTNAME
fi
if [[ -z "$HOSTNAME" ]]; then
  echo "Hostname required."
  exit 1
fi

echo "==> Routing DNS: $HOSTNAME -> tunnel $TUNNEL_NAME"
cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME" || true

cat > "$CFG" <<EOF
# Generated by scripts/volunteer-tunnel.sh — tcp ingress to localhost rpc-server only.
tunnel: $TUNNEL_ID
credentials-file: $CREDS_DIR/credentials.json

ingress:
  - hostname: $HOSTNAME
    service: tcp://127.0.0.1:$RPC_PORT
  - service: http_status:404
EOF

mkdir -p "$(dirname "$CONFIG")"
touch "$CONFIG"
if grep -q '^tunnel_host=' "$CONFIG" 2>/dev/null; then
  sed -i.bak "s|^tunnel_host=.*|tunnel_host=$HOSTNAME|" "$CONFIG"
  rm -f "$CONFIG.bak"
else
  echo "tunnel_host=$HOSTNAME" >> "$CONFIG"
fi
if ! grep -q '^transport=' "$CONFIG" 2>/dev/null; then
  echo "transport=cloudflare" >> "$CONFIG"
fi

echo ""
echo "Done."
echo "  tunnel config : $CFG"
echo "  tunnel host   : $HOSTNAME"
echo "  moontail cfg  : $CONFIG"
echo ""
echo "Next:"
echo "  export PATH=\"\$HOME/.moontail/bin:\$PATH\""
echo "  moontail setup --accept-terms"
echo ""
echo "Prompters only need moontail + weights — no cloudflared account."
